【22:41:32】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【22:41:32】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【22:41:37】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【22:41:37】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【22:43:13】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【22:44:09】      message = 调用作战dll文件出错 , exception = System.NullReferenceException: Object reference not set to an instance of an object.
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【23:33:17】      message = 调用作战dll文件出错 , exception = System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The JsonData instance has to be initialized first
   at LitJson.JsonData.EnsureCollection()
   at LitJson.JsonData.System.Collections.IEnumerable.GetEnumerator()
   at GFHelp.Mission.Map_Sent.Function.Night_PosCheck_type1(String result, Int32 toSpot) in C:\Users\jack\Desktop\CS\GFHelp-Web\Mission\Map_Sent.cs:line 59
   at GFHelp.Mission.Activity.maparctic1_4(UserData userData, Normal_MissionInfo ubti) in C:\Users\jack\Desktop\CS\GFHelp-Web\Mission\Activity.cs:line 182
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【23:33:17】      message = 调用作战dll文件出错 , exception = System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The JsonData instance has to be initialized first
   at LitJson.JsonData.EnsureCollection()
   at LitJson.JsonData.System.Collections.IEnumerable.GetEnumerator()
   at GFHelp.Mission.Map_Sent.Function.Night_PosCheck_type1(String result, Int32 toSpot) in C:\Users\jack\Desktop\CS\GFHelp-Web\Mission\Map_Sent.cs:line 59
   at GFHelp.Mission.Activity.maparctic1_4(UserData userData, Normal_MissionInfo ubti) in C:\Users\jack\Desktop\CS\GFHelp-Web\Mission\Activity.cs:line 182
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at GFHelp.Core.Action.Mission.Test(UserData userData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Action\Battle\Loop.cs:line 61
【21:53:10】      message = 删除游戏实例data出现错误. GFHelp.Core.Management.GameAccountBase , exception = System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at GFHelp.Web.Controllers.AccountController.delGameAccount(GameAccountBase gameAccountBase) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Web\Controllers\AccountController.cs:line 64
【22:03:22】      message = 解析sign出现错误 , exception = System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at GFHelp.Core.Helper.Response.Check(GameAccount gameAccount, String& result, String type, Boolean need_decode) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\Helper\ResponseCheck.cs:line 50
【22:06:32】      message = LoginDigitalSKY , exception = false System.Net.WebException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 ---> System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.UploadBits(WebRequest request, Stream readStream, Byte[] buffer, Int32 chunkSize, Byte[] header, Byte[] footer)
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadData(Uri address, String method, Byte[] data)
   at System.Net.WebClient.UploadData(String address, String method, Byte[] data)
   at GFHelp.Core.API.BaseRequset.DoPost(String url, Byte[] postData) in C:\Users\jack\Desktop\CS\GFHelp-Web\GFHelp.Core\API\BaseRequset.cs:line 40
